# Windows equivalent of regen.sh (no bash on MSVC builds): bundle index.html / style.css / app.js
# into a C++ header. Invoked by CMake as
#   cmake -DSRC=<assets dir> -DOUT=<header path> -P regen.cmake
# Unlike regen.sh's raw-string literals, the assets are emitted as NUL-terminated byte arrays:
# MSVC caps a single string literal at ~16K (C2026), which style.css/app.js exceed. The consumer-facing
# symbols stay `const char*`, so explorer_controller.h is identical on every platform. The header is
# gitignored/build-local, so the two generators never need to produce identical bytes.

foreach(_f index.html style.css app.js)
    if(NOT EXISTS "${SRC}/${_f}")
        message(FATAL_ERROR "missing asset: ${SRC}/${_f}")
    endif()
endforeach()

# 0xNN,0xNN,... with a line break every 16 bytes, NUL-terminated (consumers treat it as a C string).
# CMake regex has no {n} counted repetition, so the 16-group is spelled out.
function(asset_bytes file outvar)
    file(READ "${SRC}/${file}" _hex HEX)
    string(REGEX REPLACE "(..)" "0x\\1," _bytes "${_hex}")
    set(_b "0x..,")
    string(REGEX REPLACE "(${_b}${_b}${_b}${_b}${_b}${_b}${_b}${_b}${_b}${_b}${_b}${_b}${_b}${_b}${_b}${_b})" "\\1\n" _bytes "${_bytes}")
    set(${outvar} "${_bytes}0x00" PARENT_SCOPE)
endfunction()

asset_bytes(index.html HTML)
asset_bytes(style.css CSS)
asset_bytes(app.js JS)

string(JOIN "" _hdr
    "// AUTO-GENERATED by src/extensions/http/static/explorer/regen.cmake (Windows; Linux/macOS use regen.sh)\n"
    "// DO NOT EDIT BY HAND. Re-run after editing the asset files.\n"
    "#pragma once\n"
    "\n"
    "static const unsigned char EXPLORER_INDEX_HTML_BYTES[] = {\n${HTML}};\n"
    "inline const char* const EXPLORER_INDEX_HTML = (const char*)EXPLORER_INDEX_HTML_BYTES;\n"
    "\n"
    "static const unsigned char EXPLORER_STYLE_CSS_BYTES[] = {\n${CSS}};\n"
    "inline const char* const EXPLORER_STYLE_CSS = (const char*)EXPLORER_STYLE_CSS_BYTES;\n"
    "\n"
    "static const unsigned char EXPLORER_APP_JS_BYTES[] = {\n${JS}};\n"
    "inline const char* const EXPLORER_APP_JS = (const char*)EXPLORER_APP_JS_BYTES;\n"
)
file(WRITE "${OUT}" "${_hdr}")

message(STATUS "wrote ${OUT}")
