# Bundle explorer assets as byte arrays for MSVC builds.

foreach(asset index.html style.css app.js)
    if(NOT EXISTS "${SRC}/${asset}")
        message(FATAL_ERROR "missing asset: ${SRC}/${asset}")
    endif()
endforeach()

# Emit NUL-terminated bytes with a line break every 16 values.
function(asset_bytes file output_variable)
    file(READ "${SRC}/${file}" hex HEX)
    string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
    set(byte_pattern "0x..,")
    string(CONCAT line_pattern
        "${byte_pattern}${byte_pattern}${byte_pattern}${byte_pattern}"
        "${byte_pattern}${byte_pattern}${byte_pattern}${byte_pattern}"
        "${byte_pattern}${byte_pattern}${byte_pattern}${byte_pattern}"
        "${byte_pattern}${byte_pattern}${byte_pattern}${byte_pattern}"
    )
    string(
        REGEX REPLACE
        "(${line_pattern})"
        "\\1\n"
        bytes
        "${bytes}"
    )
    set(${output_variable} "${bytes}0x00" PARENT_SCOPE)
endfunction()

asset_bytes(index.html HTML)
asset_bytes(style.css CSS)
asset_bytes(app.js JS)

string(JOIN "" header
    "// Generated by the explorer asset bundler. Do not edit.\n"
    "#pragma once\n"
    "\n"
    "static const unsigned char EXPLORER_INDEX_HTML_BYTES[] = {\n${HTML}};\n"
    "inline const char* const EXPLORER_INDEX_HTML = (const char*)EXPLORER_INDEX_HTML_BYTES;\n"
    "\n"
    "static const unsigned char EXPLORER_STYLE_CSS_BYTES[] = {\n${CSS}};\n"
    "inline const char* const EXPLORER_STYLE_CSS = (const char*)EXPLORER_STYLE_CSS_BYTES;\n"
    "\n"
    "static const unsigned char EXPLORER_APP_JS_BYTES[] = {\n${JS}};\n"
    "inline const char* const EXPLORER_APP_JS = (const char*)EXPLORER_APP_JS_BYTES;\n"
)
file(WRITE "${OUT}" "${header}")

message(STATUS "wrote ${OUT}")
