#pragma once
// Lite-only redefine of the upstream inter-contract macros. Same names + signatures, so contract source
// stays portable to mainnet — but LATE-BOUND: dispatch to the callee's DEPLOYED code via the host
// (contractUserFunctions/Procedures tables), instead of inlining the callee. Included by the .so build
// wrapper AFTER contracts/qpi.h and the qinit-generated per-fn inputType constants, BEFORE the user
// contract. The `<Type>_<fn>_inputType` constants are generated by qinit from each callee's
// REGISTER_USER_*; the liteCall*/liteInvoke* helpers are defined in lite_dyn_abi.h.
#ifdef LITE_DYN_SO_BUILD

int liteCallFunction(const void* callerCtx, unsigned int calleeIdx, unsigned short inputType,
                     const void* in, unsigned int inSize, void* out, unsigned int outSize);
int liteInvokeProcedure(const void* callerCtx, unsigned int calleeIdx, unsigned short inputType,
                        const void* in, unsigned int inSize, void* out, unsigned int outSize,
                        long long invocationReward);

// CALL function of another (lower-index) contract — runs its deployed code, returns the result in `output`.
#undef CALL_OTHER_CONTRACT_FUNCTION_E
#define CALL_OTHER_CONTRACT_FUNCTION_E(contractStateType, function, input, output, errorVar) \
    static_assert(contractStateType::__contract_index < CONTRACT_INDEX, "lite: can only call a lower-index contract"); \
    QPI::InterContractCallError errorVar = (QPI::InterContractCallError)liteCallFunction( \
        &qpi, contractStateType::__contract_index, contractStateType##_##function##_inputType, \
        &(input), sizeof(input), &(output), sizeof(output))

#undef CALL_OTHER_CONTRACT_FUNCTION
#define CALL_OTHER_CONTRACT_FUNCTION(contractStateType, function, input, output) \
    CALL_OTHER_CONTRACT_FUNCTION_E(contractStateType, function, input, output, interContractCallError)

// INVOKE procedure of another (lower-index) contract — runs its deployed code + transfers invocationReward.
#undef INVOKE_OTHER_CONTRACT_PROCEDURE_E
#define INVOKE_OTHER_CONTRACT_PROCEDURE_E(contractStateType, procedure, input, output, invocationReward, errorVar) \
    static_assert(contractStateType::__contract_index < CONTRACT_INDEX, "lite: can only call a lower-index contract"); \
    QPI::InterContractCallError errorVar = (QPI::InterContractCallError)liteInvokeProcedure( \
        &qpi, contractStateType::__contract_index, contractStateType##_##procedure##_inputType, \
        &(input), sizeof(input), &(output), sizeof(output), (invocationReward))

#undef INVOKE_OTHER_CONTRACT_PROCEDURE
#define INVOKE_OTHER_CONTRACT_PROCEDURE(contractStateType, procedure, input, output, invocationReward) \
    INVOKE_OTHER_CONTRACT_PROCEDURE_E(contractStateType, procedure, input, output, invocationReward, interContractCallError)

#endif // LITE_DYN_SO_BUILD
