name: CI
on:
  workflow_call:
  push:
    branches: ["**"]
  pull_request:
jobs:
  build-linux:
    uses: ./.github/workflows/linux-build.yml
    with:
      configuration: Release

  build-linux-avx512:
    uses: ./.github/workflows/linux-build-avx512.yml
    with:
      configuration: Release

  build-windows:
    uses: ./.github/workflows/windows-build.yml
    with:
      configuration: Release

  windows-test-build:
    uses: ./.github/workflows/build-tests.yml

  contract-verification:
    uses: ./.github/workflows/contract-verify.yml

  platform-tests:
    uses: ./.github/workflows/platform-tests.yml

  dynamic-contract-tests:
    uses: ./.github/workflows/dynamic-contracts.yml
